Messenger/Controllers/ChatController.cs
using AutoMapper;
using Messenger.BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Messenger.DAL.Models;
using Messenger.BLL.Models;
using Messenger.PL.ViewModels;

namespace Messenger.PL.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private readonly IChatServise _chatService;
        private readonly IContactService _contactService;
        private readonly UserManager<UserEntity> _userManager;
        private readonly IMapper _mapper;

        public ChatController(IChatServise chatService, IMapper mapper, UserManager<UserEntity> userManager,IContactService contactService)
        { 
            _userManager = userManager;
            _chatService = chatService;
            _contactService = contactService;
            _mapper = mapper;
        }

        [HttpGet("chat")]
        public async Task<ActionResult> Index()
        {
            var user = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            var chatVm = _mapper.Map<IEnumerable<DisplayChats>, IEnumerable<DisplayChatsViewModel>>(await _chatService.GetAllAsync(user));

            return View(chatVm);
        }

        [HttpGet("chat/create")]
        public async Task<ActionResult> Create()
        {
            var user = (await _userManager.GetUserAsync(HttpContext.User)).Id;
            var contacts = _mapper.Map<List<Contact>,List<ContactViewModel>>((await _contactService.FindAsync(user)).ToList());

            ViewBag.Users = new SelectList(contacts, "UserId", "UserName");

            return View();
        }

        [HttpPost("chat/create")]
        public async Task<ActionResult> CreateAsync(CreateChatViewModel requestVm)
        {
            var user = (await _userManager.GetUserAsync(HttpContext.User));
            requestVm.User.Add(user);

             await _chatService.CreateAsync(_mapper.Map<CreateChatViewModel,CreateChat>(requestVm));

            return Redirect("~/chat");
        }

        [HttpPost("chat/delete")]
        public async Task<ActionResult> Delete(DeleteChatViewModel requestVm)
        {
            var user = (await _userManager.GetUserAsync(HttpContext.User));
            requestVm.UserId = user.Id;

             _chatService.DeleteAsync(_mapper.Map<DeleteChatViewModel, DeleteChat>(requestVm));

            return Redirect("~/chat");
        }
    }
}

Messenger/Controllers/ContactController.cs
using AutoMapper;
using Messenger.BLL.Interfaces;
using Messenger.BLL.Models;
using Messenger.DAL.Models;
using Messenger.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.PL.Controllers
{
    public class ContactController : Controller
    {
        private readonly IChatServise _chatService;
        private readonly IContactService _contactService;
        private readonly UserManager<UserEntity> _userManager;
        private readonly IMapper _mapper;

        public ContactController(IChatServise chatService, IMapper mapper, UserManager<UserEntity> userManager, IContactService contactService)
        {
            _userManager = userManager;
            _chatService = chatService;
            _contactService = contactService;
            _mapper = mapper;
        }

        [HttpGet("contact")]
        public async Task<IActionResult> Index()
        {
            var user = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            var chatVm = _mapper.Map<IEnumerable<Contact>, IEnumerable<ContactViewModel>>(await _contactService.GetPagedAsync(user));

            return View(chatVm);
        }

        [HttpGet("contact/error")]
        public IActionResult Error()
        {
            return View();
        }


        [HttpGet("contact/addcontact")]
        public  ActionResult Create()
        {
            return View();
        }

        [HttpPost("contact/addcontact")]
        public async Task<ActionResult> CreateAsync(ContactViewModel requestVm)
        {
            var request = await _userManager.GetUserAsync(HttpContext.User);
            //if (request.Email == requestVm.UserEmail)
            //{
            //    return Redirect("~/contact/error");
            //}
            
                requestVm.OwnerId = request.Id;

                var create = await _contactService.CreateAsync(_mapper.Map<ContactViewModel, Contact>(requestVm));

                if (create)
                {
                    return Redirect("~/contact");
                }
                else
                {
                    return Redirect("~/contact/error");
                }
            
        }

        [HttpGet("contact/delete/{id}")]
        public async Task<ActionResult> Delete(Guid id)
        {
            _contactService.DeleteAsync(id);
            return View();
        }

    }
}

Messenger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    @using Microsoft.AspNetCore.Mvc.Localization

    @inject IViewLocalizer Localizer

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MessengerApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-utilities.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Messenger</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">@Localizer["Login"]</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register"> @Localizer["Registration"] </a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Chat" asp-action="Create">@Localizer["Start_new_chat/group"]  </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Contact" asp-action="Create"> @Localizer["Add contact"]  </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Contact" asp-action="Index"> @Localizer["My contacts"]  </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Chat" asp-action="Index"> @Localizer["My chats"]  </a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link text-white" asp-controller="Account" asp-action="Profile">@User.Identity.Name </a>
                            </li>

                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input class=".bg-dark nav-link text-dark" type="submit" value="@Localizer["Logout"]" />
                                </form>
                            </li>
                        }
                        <li class="nav-item">
                            @await Html.PartialAsync("_SelectLanguagePartial")
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Messenger/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:20px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    Language: <select name="culture" onchange="this.form.submit();"
                      asp-for="@requestCulture.RequestCulture.UICulture.Name"
                      asp-items="cultureItems"></select>
</form>