Messenger/ViewModels/Account/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.PL.ViewModels.Account
{
    public class ChangePasswordViewModel
    {
        public string  Id { get; set; }
        public string Email { get; set; }
        public string NewPassword { get; set; }

    }
}

Messenger/ViewModels/Account/UserViewModel.cs
using Microsoft.AspNetCore.Identity;
using System;

namespace Messenger.PL.ViewModels
{
    public class UserViewModel : IdentityUser<Guid>
    {

    }
}

Messenger/Controllers/RolesController.cs
using Messenger.DAL.Models;
using Messenger.PL.ViewModels.Account;
using Messenger.PL.ViewModels.Admin;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.PL.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<RoleEntity> _roleManager;
        UserManager<UserEntity> _userManager;

        public RolesController(RoleManager<RoleEntity> roleManager, UserManager<UserEntity> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index(int page = 1) {

            var result = new AdminRolesViewModel();

            if (page == 1)
            {
                result.TotalCount = _roleManager.Roles.Count();
            }


            result.Roles  = _roleManager.Roles.Skip((page - 1) * 15).ToList();

            result.Page = page;

            return View(result);
       }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new RoleEntity { Name = name });
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            RoleEntity role = await _roleManager.FindByNameAsync(id.ToString());
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            UserEntity user = await _userManager.FindByIdAsync(userId.ToString());
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Guid userId, List<string> roles)
        {
            // получаем пользователя
            UserEntity user = await _userManager.FindByIdAsync(userId.ToString());
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return Redirect("~/Users/Index");
            }

            return NotFound();
        }
    }
}

Messenger/Controllers/UsersController.cs
using Messenger.DAL.Models;
using Messenger.PL.ViewModels.Account;
using Messenger.PL.ViewModels.Admin;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Messenger.PL.Controllers
{
    public class UsersController : Controller
    {
        UserManager<UserEntity> _userManager;

        public UsersController(UserManager<UserEntity> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index(int page = 1)
        {

            var result = new AdminUsersViewModel();

            if (page == 1)
            {
                result.TotalCount = _userManager.Users.Count();
            }


            result.Users = _userManager.Users.Skip((page - 1) * 15).ToList();

            result.Page = page;

            return View(result);
        }
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserEntity user = new UserEntity { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet("users/edit/{id}")]
        public async Task<IActionResult> Edit(string id)
        {
            UserEntity user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost("users/edit/{id}")]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserEntity user = await _userManager.FindByIdAsync(model.Id.ToString());
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(Guid id)
        {
            UserEntity user = await _userManager.FindByIdAsync(id.ToString());
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(Guid id)
        {
            UserEntity user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserEntity user = await _userManager.FindByIdAsync(model.Id.ToString());
                if (user != null)
                {
                    var _passwordValidator =
                    HttpContext.RequestServices.GetService(typeof(IPasswordValidator<UserEntity>)) as IPasswordValidator<UserEntity>;
                    var _passwordHasher =
                    HttpContext.RequestServices.GetService(typeof(IPasswordHasher<UserEntity>)) as IPasswordHasher<UserEntity>;

                    IdentityResult result =
                    await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Користувач не знайдений");
                }
            }
            return View(model);
        }
    }
}

Messenger/Views/Users/ChangePassword.cshtml
@model Messenger.PL.ViewModels.Account.ChangePasswordViewModel
@{
    ViewBag.Title = "Зиіна пароля";
}
<h2>Зміна пароля для користувача @Model.Email</h2>
<form asp-action="ChangePassword" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Email" />

    <div class="form-group">
        <label asp-for="NewPassword" class="control-label">Новий пароль</label>
        <input type="text" asp-for="NewPassword" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Зберігти" class="btn btn-outline-dark" />
    </div>
</form>

Messenger/Views/Users/Create.cshtml
@model Messenger.PL.ViewModels.Account.CreateUserViewModel
@{
    ViewBag.Title = "Добавление пользователя";
}
<form asp-action="Create" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Пароль</label>
        <input type="password" asp-for="Password" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-outline-secondary" />
    </div>
</form>

Messenger/Views/Users/Edit.cshtml
@model Messenger.PL.ViewModels.Account.EditUserViewModel
@{
    ViewBag.Title = "Редактирование пользователя";
}
<form asp-action="Edit" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>

Messenger/Views/Users/Index.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@using Messenger.PL.ViewModels.Admin;
@model AdminUsersViewModel

<div class="list-group">
    @foreach (var item in Model.Users)
    {
    <div class="my-10">
        <a href=@("/users/edit/" + item.Id) class="list-group-item list-group-item-action">@item.UserName</a>
        <a  class="btn btn-primary" asp-area="" asp-route-userid="@item.Id" asp-controller="Roles" asp-action="Edit">Редагувати ролі</a>

        <form method="post" asp-action="Delete" asp-route-id="@item.Id" class="btn-group-sm">
            <input type="hidden" asp-for="@item.Id" />
            <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Видалити цю роль?')" />
        </form>
    </div>
    }
</div>
<div class="btn-group" role="group" aria-label="Page">
    @if (Model.Page > 1)
    {
<a type="button"
   href="@Url.Action("Index", "Roles", new { page = Model.Page - 1 })"
   class="btn btn-outline-primary">Previous</a>}

    @if (Model.TotalCount > Model.PageSize * Model.Page)
    {
<a type="button"
   href="@Url.Action("Index", "Roles", new { page = Model.Page + 1 })"
   class="btn btn-primary">Next</a>}
</div>